import { renderFlatSvg } from "@/lib/flats/render";
import { RIVIERA_HOODIE, type FlatSpecV1 } from "@/lib/flats/spec";
import type { FlatView } from "@/lib/flats/templates/hoodie";

/**
 * The real parametric flat, rendered server-side into the page.
 *
 * This is the only product image on the site that is literally the product's
 * output — the same `renderFlatSvg` the workspace and the factory PDF use, so
 * it cannot drift from what a customer would get. `lib/flats/**` is
 * isomorphic (no server-only, no database), which is what makes this safe in
 * a static page.
 */
export function FlatFigure({
  view = "front",
  fill,
  ink,
  spec = RIVIERA_HOODIE,
  className,
}: {
  view?: FlatView;
  fill?: string;
  ink?: string;
  spec?: FlatSpecV1;
  className?: string;
}) {
  const svg = renderFlatSvg(spec, view, { fill, ink });
  return (
    <div
      className={className ? `mk-flat ${className}` : "mk-flat"}
      // Generated by our own deterministic renderer from an enum-only spec;
      // there is no user content in this string.
      dangerouslySetInnerHTML={{ __html: svg }}
    />
  );
}
